version: '3.7'

services:
  golden-hammer-shared:
    command: ['npm', 'run', 'dev-linked']
    volumes:
      - ../.docker/.npmrc-localRegistry:/app/.npmrc
      # Watchdir for nfg-util updates
      - ../../../general/nfg-util/.trigger_nfg_util:/links/nfg-util/.trigger_nfg_util
    networks:
      - nfg-util_registry

networks:
  nfg-util_registry:
    external: true
