version: '3.7'

services:
  golden-hammer-shared:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nfg/golden-hammer-shared:latest
    tty: true
    command: 'npm run docker-compose'
    environment:
      - TERM=xterm-256color
      - NPM_CONFIG_PREFIX=./node_modules/.npm-global
