version: '3.7'

services:
  golden-hammer-shared:
    image: nfg/golden-hammer-shared:latest
    tty: true
    environment:
      - TERM=xterm-256color
      - NPM_CONFIG_PREFIX=./node_modules/.npm-global
