version: '3.7'

services:
  update-deps:
    image: node:18-alpine3.18
    container_name: update-deps
    command: 'tail -f /dev/null'
    user: '1000'
    working_dir: '/app'
    volumes:
      - '.:/app'
