version: '3.7'

services:
  golden-hammer-shared:
    build:
      target: development
    command: ['npm', 'run', 'dev']
    volumes:
      - .:/build
      # - /build/node_modules
    environment:
      - NODE_OPTIONS=--enable-source-maps --trace-warnings
