version: '3.7'

services:
  golden-hammer-shared:
    command: ['npm', 'run', 'dev:linked']
    volumes:
      - ../../../general/nfg-util/:/nfg-util
      # - /dev/null:/app/.git # For git submodules
      # - /app/node_modules
