version: '3.7'

services:
  golden-hammer-shared:
    image: nfg/golden-hammer-shared:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      # - /app/node_modules
    # environment:
    #   - TERM=xterm-256color
