version: '3.7'

services:
  golden-hammer-shared:
    image: hangouthere/golden-hammer-shared:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    user: '1000'
    working_dir: '/app'
    volumes:
      - .:/app
