version: '3.7'

services:
  golden-hammer-shared:
    volumes:
      - ./.docker/.npmrc-localRegistry:/app/.npmrc
    networks:
      - nfg-util_registry

networks:
  nfg-util_registry:
    external: true
